baseURL: "http://ecumenopolis.net"
disableKinds: ["taxonomy", "taxonomyTerm"]

languageCode: "en-us"
DefaultContentLanguage: "en"
title: "The Book of Ecumenopolis"
theme: "book"

hasCJKLanguage: false
metaDataFormat: "yaml"

pygmentsUseClasses: true
pygmentsCodefences: true

defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false

Params:
  # (Optional, default true) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC: true

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection: '*'

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS: true

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/ecumenopolis/suggestions

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: edit/master/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "Jan 2, 2006"

# Global menu section
menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
  